ROOT: ../../dataArcticnet
ITER_TF: 1

# Training setting
N_CLASSES: 6
CROPSIZE: 30
BATCH_SIZE: 1000
IGNORE_LABEL: 6
EPOCH_START: 1
EPOCH_MAX: 500
ITER_SIZE: 1
LR: 0.0001
POLY_POWER: 4
WEIGHT_DECAY: 2.0e-5
MOMENTUM: 0.5

FUSEMODE: midFuse_layer3
# lateFuse, midFuse_layer2, midFuse_layer3 or earlyFuse
EXPERIENT: try_fusenet_midFuse_layer3
NUM_WORKERS: 4

TESTON: False
MAPGENEON: False